### ISSUE TITLE
Pagination details

### ISSUE THREAD

**Issue by funkydev** [allegro/restapi-guideline#6]
How to return the pagination details for resources? Client needs to know how much resources are available for calculating page numbers. Do you have any suggestions?

**Comment by Zenedith** [comment]
It is described in [wrap-collection-in-object](https://github.com/allegro/restapi-guideline/blob/master/Representation.md#wrap-collection-in-object) section.
For example, you could add information about `count`, `limit` (from request) and `offset` (from request) like this:

```
{
    "offers": [
        {
            "id": "01234567-89ab-cdef-0123-456789abcdef",
            "name": "PINK FLOYD: THE ENDLESS RIVER"
        },
        {
            "id": "11234567-89ab-cdef-0123-456789abcdef",
            "name": "Ufomammut - Eve"
        }
    ],
    "count": 4674,
    "limit": 0,
    "offset": 100
}
```

Base on this informations you can calculate whatever you need.

**Comment by walec51** [comment]
This type of pagination can dramatically impact performance of large data sets like offers what are handled by NoSQL databases and therefore should not be implemented.

An simplified pagination scheme with a nextPage identifier is much better performance wise. Especially if filters are involved calculating count and ordering results for the limit/offset scheme is very costly.

**Comment by Zenedith** [comment]
For NoSQL databases without "good" support for "pagination" You can index yours data in more efficient database like [Elasticsearch](https://www.elastic.co/).
You can also use cache on many levels to achieve good performance, even for fast changing resources.

There are some "problems" with `nextPage` for me:
- you can't ask for many "pages" at once (You must wait for returned data to get next page handle id)
- it may be hard to return total "count"

In general -  everything depends on the context and API features should not be dependant from currently used database

**Comment by walec51** [comment]
yes, you can always solve a problem by adding more hardware, middleware and ppl to maintain this functionality - but I don't think its worth it for most cases

Google for example looks like it has pagination in their search results but its actually not accurate. It will show you a link to "page 12" for example but if the results turn out to be fewer in numbers it will redirect you do "page 9".

As for your arguments:

* you can use `limit` with `nextPage` to return more results at once,
* counting "count" every time is a big performerce bottleneck if filtering is used on large datasets - you have to search though your indexes - top to bottom - for each request
